config/routes.rb
Ibiryo::Application.routes.draw do
  resources :food_searches

  resources :carts do
    resources :line_items
  end

  resources :marketing_strategies

  resources :feedbacks

  resources :shops do
    resources :menus
    resources :options
    resources :choices
  end

  resources :menus do
    resources :menu_sections
  end

  resources :menu_sections do
    resources :items
  end

  match 'contact' => 'feedbacks#new'
  match 'about' => 'pages#about'
  match 'security' => 'pages#security'
  match 'help' => 'pages#help'
  match 'legal' => 'pages#legal'

  devise_for :users do
    get '/login' => "devise/sessions#new"
    get '/start' => "devise/registrations#new"
  end

  root to: "pages#index"

end

app/models/shop_related/choice.rb
class Choice < Describable
  belongs_to :shop
  attr_accessible :is_active, :price
  attr_accessible   :is_active
  validates         :is_active,
                    :inclusion => { :in => [true, false],
                                  :message => I18n.t("shops_shared.form.errors.is_active")}
  validates         :price, :numericality => { greater_than_or_equal_to: 0 }
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  load_and_authorize_resource
  before_filter :set_choices

  # GET /choices/new
  # GET /choices/new.json
  def new
    @choice = Choice.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /choices/1/edit
  def edit
    @choice = @choices.find(params[:id])
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = @choices.new(params[:choice])

    respond_to do |format|
      if @choice.save
        format.html { redirect_to new_shop_choice_path(@shop), notice: t("choices.update.notice_success") }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /choices/1
  # PUT /choices/1.json
  def update
    @choice = @choices.find(params[:id])

    respond_to do |format|
      if @choice.update_attributes(params[:choice])
        format.html { redirect_to @shop, notice: t("choices.update.notice_success") }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    @choice = @choices.find(params[:id])
    @choice.destroy

    respond_to do |format|
      format.html { redirect_to choices_url }
    end
  end

private

  def set_choices
    set_parent_from_nested_route(Shop)
    set_stuck_shop(@shop)
    @choices = @shop.choices
  end
end

app/helpers/choices_helper.rb
module ChoicesHelper

  def choice_price(choice)
    price = (choice.price > 0) ? number_to_shop_currency(choice.price, choice.shop) : t("general.free")
  end

end

app/views/choices/_form.html.erb
<%= simple_nested_form_for([@shop, @choice], :html => {:class => "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= render 'shops_shared/is_active', obj: @choice, f: f %>
    <%= f.input :price %>
    <%= render 'descriptions/section', f: f, klasses: "choices", klass_instance: @choice %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/choices/_index.html.erb
<h2><%= t("shops.show.options.choices.title") %></h2>

<table class="table table-striped table-hover">
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Is active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% choices.each do |choice| %>
  <tr>
    <td><%= choice.name %></td>
    <td><%= choice.price %></td>
    <td><%= choice.is_active %></td>
    <td><%= link_to 'Edit', edit_shop_choice_path(choice.shop), class: "btn btn-info btn-mini" %></td>
    <td><%= link_to 'Destroy', shop_choice_path(choice.shop, choice), method: :delete,
                                data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-mini" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Choice', new_shop_choice_path(@shop), class: "btn" %>

app/views/choices/_show.html.erb
<% if start_choice_row?(count) %>
  <div class="clearfix"></div>
  <div class="row-fluid">
<% end %>
<div class="span4">
  <div class="row-fluid">
    <div class="span2"><%= button %></div>
    <div class="span10 choice"><%= name %></div>
  </div>
  <div class="row-fluid">
    <div class="span2"></div>
    <div class="span10 muted"><small><%= "#{t("option_selections.add")} #{price}" %></small></div>
  </div>
</div>
<% if end_choice_row?(count) or count == num_options - 1 %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1><%= t("choices.edit.title", choice: @choice.name) %></h1>

<%= render 'form' %>

app/views/choices/new.html.erb
<h1><%= t("choices.new.title") %></h1>

<%= render 'form' %>