config/routes.rb
Ibiryo::Application.routes.draw do
  resources :food_searches

  resources :carts do
    resources :line_items
  end

  resources :marketing_strategies

  resources :feedbacks

  resources :shops do
    resources :menus
    resources :options
    resources :choices
  end

  resources :menus do
    resources :menu_sections
  end

  resources :menu_sections do
    resources :items
  end

  match 'contact' => 'feedbacks#new'
  match 'about' => 'pages#about'
  match 'security' => 'pages#security'
  match 'help' => 'pages#help'
  match 'legal' => 'pages#legal'

  devise_for :users do
    get '/login' => "devise/sessions#new"
    get '/start' => "devise/registrations#new"
  end

  root to: "pages#index"

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :user
  attr_accessible :body, :first_name, :last_name, :subject
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  load_and_authorize_resource
  before_filter :set_feedbacks

  # GET /feedbacks
  # GET /feedbacks.json
  def index

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = @feedbacks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = @feedbacks.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = @feedbacks.new(params[:feedback])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = @feedbacks.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = @feedbacks.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url }
    end
  end
private

  def set_feedbacks
    scoped_for_shopper(Feedback)
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= simple_form_for(@feedback, :html => {:class => "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :subject %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table>
  <tr>
    <th>User</th>
    <th>Body</th>
    <th>Email</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Subject</th>
    <th>Ip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.user %></td>
    <td><%= feedback.body %></td>
    <td><%= feedback.email %></td>
    <td><%= feedback.first_name %></td>
    <td><%= feedback.last_name %></td>
    <td><%= feedback.subject %></td>
    <td><%= feedback.ip %></td>
    <td><%= link_to 'Show', feedback %></td>
    <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
    <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @feedback.user %>
</p>

<p>
  <b>Body:</b>
  <%= @feedback.body %>
</p>

<p>
  <b>Email:</b>
  <%= @feedback.email %>
</p>

<p>
  <b>First name:</b>
  <%= @feedback.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @feedback.last_name %>
</p>

<p>
  <b>Subject:</b>
  <%= @feedback.subject %>
</p>

<p>
  <b>Ip:</b>
  <%= @feedback.ip %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>