config/routes.rb
Ibiryo::Application.routes.draw do
  resources :food_searches

  resources :carts do
    resources :line_items
  end

  resources :marketing_strategies

  resources :feedbacks

  resources :shops do
    resources :menus
    resources :options
    resources :choices
  end

  resources :menus do
    resources :menu_sections
  end

  resources :menu_sections do
    resources :items
  end

  match 'contact' => 'feedbacks#new'
  match 'about' => 'pages#about'
  match 'security' => 'pages#security'
  match 'help' => 'pages#help'
  match 'legal' => 'pages#legal'

  devise_for :users do
    get '/login' => "devise/sessions#new"
    get '/start' => "devise/registrations#new"
  end

  root to: "pages#index"

end

app/models/shop_related/menu_section.rb
class MenuSection < Describable
  belongs_to        :menu
  has_many          :items
  attr_accessible   :is_active
  validates         :is_active,
                    :inclusion => { :in => [true, false],
                                  :message => I18n.t("shops_shared.form.errors.is_active")}
end

app/controllers/menu_sections_controller.rb
class MenuSectionsController < ApplicationController
  load_and_authorize_resource
  before_filter :set_menu_sections, except: [:new]
  # GET /menu_sections
  # GET /menu_sections.json
  def index
    @menu_sections = @menu_sections.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /menu_sections/1
  # GET /menu_sections/1.json
  def show
    @menu_section = @menu_sections.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /menu_sections/new
  # GET /menu_sections/new.json
  def new
    @menu_section = MenuSection.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /menu_sections/1/edit
  def edit
    @menu_section = @menu_sections.find(params[:id])
  end

  # POST /menu_sections
  # POST /menu_sections.json
  def create
    @menu_section = @menu_sections.new(params[:menu_section])

    respond_to do |format|
      if @menu_section.save
        format.html { redirect_to new_menu_section_item_path(@menu_section),
                                  notice: t("menu_sections.create.notice_success") }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /menu_sections/1
  # PUT /menu_sections/1.json
  def update
    @menu_section = @menu_sections.find(params[:id])

    respond_to do |format|
      if @menu_section.update_attributes(params[:menu_section])
        format.html { redirect_to @menu.shop, notice: t("menu_sections.create.notice_success") }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /menu_sections/1
  # DELETE /menu_sections/1.json
  def destroy
    @menu_section = @menu_sections.find(params[:id])
    @menu_section.destroy

    respond_to do |format|
      format.html { redirect_to menu_sections_url }
    end
  end

private
  def set_menu_sections
    set_parent_from_nested_route(Menu)
    set_stuck_shop(@menu.shop)
    @menu_sections = @menu.menu_sections
  end

end

app/helpers/menu_sections_helper.rb
module MenuSectionsHelper
end

app/views/menu_sections/_form.html.erb
<%= simple_nested_form_for([@menu, @menu_section], :html => {:class => "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= render 'shops_shared/is_active', obj: @menu_section, f: f %>
    <%= render 'descriptions/section', f: f, klasses: "menu_sections", klass_instance: @menu_section %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/menu_sections/_show.html.erb
<h4><%= menu_section.name %></h4>
<% unless menu_section.description.blank? %>
  <h6><%= menu_section.description %></h6>
<% end %>

<% if can_and_want_see_everything? %>
    <div class="row-fluid pager">
      <%= link_to t("menu_sections.show.edit", name: menu_section.name),
                  edit_menu_menu_section_path(menu_section.menu, menu_section), class: "btn btn-link" %> or
      <%= link_to t("menu_sections.show.add_item", menu: menu_section.menu.name),
                  new_menu_section_item_path(menu_section), class: "btn btn-link" %>
    </div>
<% end %>


<%= render 'items/index', items: items(menu_section)%>

app/views/menu_sections/edit.html.erb
<h1><%= t("menu_sections.edit.title", menu: @menu_section.name) %></h1>

<%= render 'form' %>

app/views/menu_sections/index.html.erb
<h1>Listing menu_sections</h1>

<table>
  <tr>
    <th>Menu</th>
    <th>Is active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menu_sections.each do |menu_section| %>
  <tr>
    <td><%= menu_section.menu %></td>
    <td><%= menu_section.is_active %></td>
    <td><%= link_to 'Show', menu_section %></td>
    <td><%= link_to 'Edit', edit_menu_section_path(menu_section) %></td>
    <td><%= link_to 'Destroy', menu_section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu section', new_menu_section_path %>

app/views/menu_sections/new.html.erb
<h1><%= t("menu_sections.new.title", menu: @menu.name) %></h1>

<%= render 'form' %>