config/routes.rb
Ibiryo::Application.routes.draw do
  resources :food_searches

  resources :carts do
    resources :line_items
  end

  resources :marketing_strategies

  resources :feedbacks

  resources :shops do
    resources :menus
    resources :options
    resources :choices
  end

  resources :menus do
    resources :menu_sections
  end

  resources :menu_sections do
    resources :items
  end

  match 'contact' => 'feedbacks#new'
  match 'about' => 'pages#about'
  match 'security' => 'pages#security'
  match 'help' => 'pages#help'
  match 'legal' => 'pages#legal'

  devise_for :users do
    get '/login' => "devise/sessions#new"
    get '/start' => "devise/registrations#new"
  end

  root to: "pages#index"

end

app/models/cart_related/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to        :cart
  belongs_to        :item
  has_many          :option_selections
  accepts_nested_attributes_for :option_selections
  attr_accessible   :booked_for,                  :description_at_checkout,     :name_at_checkout,      :quantity,
                    :special_instructions,        :unit_price_at_checkout,      :item_id,               :cart_id,
                    :option_selections_attributes


  def update_options(option_selections)
    unless option_selections.blank?
      option_selections.each do |key, attributes|
        choice_ids = attributes.delete(:choice_ids)
        option = self.option_selections.create!(attributes)
        option.update_attributes(choice_ids: choice_ids)
      end
    end
  end

  def subtotal
    total = item.price * quantity
    option_selections.each do |option_selection|
      total += option_selection.subtotal
    end
    total
  end


end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  load_and_authorize_resource
  before_filter :set_line_items

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = @line_items.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    #raise params.to_yaml
    @line_item = @line_items.build(params[:line_item])
    option_selection = params[:line_item].delete(:option_selections_attributes)

    respond_to do |format|
      if @line_item.save
        @line_item.update_options(option_selection) #if option_selection.present?
        format.html { redirect_to @cart.shop, notice: t("line_items.create.notice_success") }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = @line_items.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @cart.shop, notice: t("line_items.update.notice_success") }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = line_items.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
    end
  end

private

  def set_line_items
    set_parent_from_nested_route(Cart)
    @line_items = @cart.line_items
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<div class="modal hide fade" id=<%="item-#{item.id}"%>>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Add item to shopping cart</h3>
    <h4><%= "#{item.name} - #{shop_price(item)}" %></h4>
  </div>
  <%= simple_form_for([@cart, @line_item]) do |f| %>
    <div class="modal-body">
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.hidden_field :cart_id, { :value => @cart.id } %>
        <%= f.hidden_field :item_id, { :value => item.id } %>
        <%= render "option_selections/form", num_cols: 3, options: item.options, f: f %>

        <%= f.input :quantity, :input_html => { value: 1 } %>
        <%= f.input :special_instructions,
                    :input_html => { rows: 10, placeholder: "For example: \"no onions or peppers\"" } %>
      </div>
    </div>
    <div class="modal-footer form-actions">
      <%= f.button :submit, "Add to cart", class: "pull-left btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/line_items/_index.html.erb
<table class="table table-striped">
  <tr>
    <th>Item</th>
    <th>Description</th>
    <th>Quantity</th>
    <th>Price</th>
    <th></th>
  </tr>

  <% line_items.each do |line_item| %>
    <tr>
      <td><%= line_item.item.name %></td>
      <td>
        <%= line_item.item.description %>
        <small><%= render "option_selections/index", option_selections: line_item.option_selections %></small>
        <% unless line_item.special_instructions.blank? %>
          <br/>
          <strong><%= t("carts.shared.special_instructions") %>: </strong>
          <%= line_item.special_instructions %>
        <% end %>
      </td>
      <td><%= line_item.quantity %></td>
      <td><%= number_to_shop_currency(line_item.subtotal, @shop) %></td>
      <td><%= link_to t("carts.edit.remove_item"), cart_line_item_path(@cart),
                                  method: :delete, data: { confirm: 'Are you sure?' },
                                  class: "btn btn-danger btn-mini" %></td>
    </tr>
  <% end %>
  <tr class="info">
    <td colspan=3><strong><%= t("shops.shared.subtotal") %></strong></td>
    <td colspan=2><strong><%= number_to_shop_currency(@cart.subtotal, @shop) %></strong></td>
  </tr>
</table>

app/views/line_items/_index_side.html.erb
<span class="pull-left" style="width: 30px; text-align: center;">Qty</span>
<span class="pull-left" style="padding-left: 15px;">Item</span>
<span class="pull-right" style="text-align: right; padding-right: 15px;">Price</span>
<div class="clearfix"></div>
<% line_items.each do |line| %>
  <%= render "line_items/show_side", line_item: line %>
<% end %>

app/views/line_items/_show_side.html.erb
<div class="alert alert-info line_item-side">
  <span class="pull-left" style="width: 20px; text-align: center;"><%= line_item.quantity %></span>
  <span class="pull-left" style="padding-left: 15px;"><%= truncate(line_item.item.name, length: 17) %></span>
  <span class="pull-right" style="text-align: right;"><%= number_to_shop_currency(line_item.subtotal, line_item.cart.shop) %></span>
  <div class="clearfix"></div>
</div>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cart:</b>
  <%= @line_item.cart %>
</p>

<p>
  <b>Item:</b>
  <%= @line_item.item %>
</p>

<p>
  <b>Special instructions:</b>
  <%= @line_item.special_instructions %>
</p>

<p>
  <b>Quantity:</b>
  <%= @line_item.quantity %>
</p>

<p>
  <b>Unit price at checkout:</b>
  <%= @line_item.unit_price_at_checkout %>
</p>

<p>
  <b>Name at checkout:</b>
  <%= @line_item.name_at_checkout %>
</p>

<p>
  <b>Description at checkout:</b>
  <%= @line_item.description_at_checkout %>
</p>

<p>
  <b>Booked for:</b>
  <%= @line_item.booked_for %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>